### PR TITLE
new-feature:add k3rangeset

### PR DESCRIPTION
**Pull request by IloveKanade**
The k3rangeset been modified according to the specification

### CODE REVIEW

**Comment by drmingdrmer** [comment]
@IloveKanade @pengsven 
Have you guys ever thought of another better name for these stuff?

The type names in this package smell like a ... 🤔 

And I am not sure whether it'll better to have these type in different packages.
What you say? guys

**Comment by drmingdrmer** [comment]
**Span** may be better than **range**.

**Comment by IloveKanade** [comment]
> **Span** may be better than **range**.

The point is that a lot of the classes and methods in this project are named range, so it would be confusing if we didn't have the same names？

**Comment by drmingdrmer** [comment]
> > **Span** may be better than **range**.
> 
> The point is that a lot of the classes and methods in this project are named range, so it would be confusing if we didn't have the same names？

Hm... so... what are you supposing to do?

As far as I know, renaming is quite easy in CLion. And it is able to rename the word in comments as well when you renaming a class or function. 
Is this what you are concerning?

P.S. you can have a CLion free-trial license for 30 days!

**Review by drmingdrmer — APPROVED** [review]

**Comment by drmingdrmer** [comment]
LGTM!

**Pull request merged**
